// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohpsotlyjscqkcbxjazc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ocHNvdGx5anNjcWtjYnhqYXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzU4MDAsImV4cCI6MjA2MTAxMTgwMH0.ZPJmXocoQO1zhE6CJc5TZ3VFWinFjQa7xRlBX7m2bCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);